### ISSUE TITLE
Postgres - wrong path 

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/executors#61]
Steps to reproduce:
```
docker build -t postgres .
docker run -it postgres 
```

Logs:
```
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWxxxxxxxxxOMMMMMNxxxxxxxxx0MMMMMKddddddxkKWMMMMMMMMMMMMXOxdddxONMMMM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllo0MMMMMMMM0olllllllllo0MM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOlllllllllllloWMMMMMdllllllllllllldM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllllloMMMM0lllllllllllllllK
MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllllKMMM0lllllllllllllllO
MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMollllllllllllllO
MWOkkkkk0MMMKlllllllllkMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMxlllllllllllllO
NkkkkkkkkkMMKlllllllloMMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMMWOdolllllllllO
KkkkkkkkkkNMKllllllldMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MOkkkkkkk0MMKllllldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMWX00KXMMMMXxk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

▶️  /usr/local/bin/jina executor --uses config.yml --entrypoint /bin/bash
🔧️                            cli = executor                      
                    ctrl-with-ipc = False                         
                           daemon = False                         
                   disable-remote = False                         
                    docker-kwargs = None                          
                  dynamic-routing = True                          
               dynamic-routing-in = False                         
              dynamic-routing-out = False                         
🔧️                     entrypoint = /bin/bash                     
                              env = None                          
                    expose-public = False                         
                         external = False                         
                             gpus = None                          
                             host = 0.0.0.0                       
                          host-in = 0.0.0.0                       
                         host-out = 0.0.0.0                       
                 hosts-in-connect = None                          
                         identity = a14534af-3119-4067-a36c-579aaa
                       log-config = /usr/local/lib/python3.7/site-
                       memory-hwm = -1                            
                             name = None                          
                 noblock-on-start = False                         
                         num-part = 0                             
                on-error-strategy = IGNORE                        
                         parallel = 1                             
                           pea-id = 0                             
                         pea-role = SINGLETON                     
                       peas-hosts = None                          
                         pod-role = None                          
                          polling = ANY                           
                        port-ctrl = 55837                         
                      port-expose = 55023                         
                          port-in = 55661                         
                         port-out = 49489                         
                            proxy = False                         
                      pull-latest = False                         
                       py-modules = None                          
                            quiet = False                         
                      quiet-error = False                         
                quiet-remote-logs = False                         
                         replicas = 1                             
                   runs-in-docker = False                         
                  runtime-backend = PROCESS                       
                      runtime-cls = ZEDRuntime                    
                       scheduling = LOAD_BALANCE                  
                        socket-in = PULL_BIND                     
                       socket-out = PUSH_BIND                     
                      ssh-keyfile = None                          
                     ssh-password = None                          
                       ssh-server = None                          
                     timeout-ctrl = 5000                          
                    timeout-ready = 600000                        
                     upload-files = None                          
🔧️                           uses = config.yml                    
                       uses-after = None                          
                      uses-before = None                          
                       uses-metas = None                          
                        uses-with = None                          
                          volumes = None                          
                        workspace = None                          
                     workspace-id = 50ee0c3d-4506-40de-94bc-e785f5
                     zmq-identity = None                          

UserWarning: Install `uvloop` via `pip install "jina[uvloop]"` for better performance. (raised from /usr/local/lib/python3.7/site-packages/jina/helper.py:828)
     ZEDRuntime@17[C]:can not load the executor from config.yml
        BasePea@17[E]:ExecutorFailToLoad() during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jina/importer.py", line 201, in _path_import
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/postgres.py", line 11, in <module>
    from .postgreshandler import PostgreSQLHandler
ImportError: attempted relative import with no known parent package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 91, in _load_executor
    runtime_args=vars(self.args),
  File "/usr/local/lib/python3.7/site-packages/jina/jaml/__init__.py", line 547, in load_config
    extra_search_paths=(os.path.dirname(s_path),) if s_path else None,
  File "/usr/local/lib/python3.7/site-packages/jina/jaml/helper.py", line 241, in load_py_modules
    PathImporter.add_modules(*mod)
  File "/usr/local/lib/python3.7/site-packages/jina/importer.py", line 171, in add_modules
    module = PathImporter._path_import(p)
  File "/usr/local/lib/python3.7/site-packages/jina/importer.py", line 203, in _path_import
    raise ImportError(f'can not import module from {absolute_path}') from ex
ImportError: can not import module from /workspace/postgres.py

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 83, in run
    timeout_ctrl=timeout_ctrl,
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 59, in __init__
    self._load_executor()
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 104, in _load_executor
    raise ExecutorFailToLoad from ex
jina.excepts.ExecutorFailToLoad
Traceback (most recent call last):
  File "/usr/local/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/cli/__init__.py", line 119, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/usr/local/lib/python3.7/site-packages/cli/api.py", line 29, in pea
    with Pea(args) as p:
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 364, in __enter__
    return self.start()
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 204, in start
    self.wait_start_success()
  File "/usr/local/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 276, in wait_start_success
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
```

**Comment by tadejsv** [comment]
Some context:
- this is actually a problem with relative imports from scripts in the main folder, see https://stackoverflow.com/questions/16981921/relative-imports-in-python-3
- A solution is to switch from relative to absolute imports, i.e. `from a import x` instead of `from .a import x`
- At the same time, pytest must be run as `python -m pytest`. See here https://docs.pytest.org/en/latest/how-to/usage.html#calling-pytest-through-python-m-pytest

A true solution would be to make each executor a package, and install it. But as this is not wanted for now, we must use the solution outlined above.

**Comment by CatStark** [comment]
Solved by https://github.com/jina-ai/executors/pull/69
